# application.properties - 이름 기억해두기!
# 이 파일은 항상 resource 폴더 바로 아래 만든다.
# 목적: 스프링 서버가 실행될 때 설정을 로딩하는 파일이다.
# 주석은 #을 이용한다.
# 참고: properties 파일 인코딩이 깨질 때는 - 설정 -> '인코딩' 검색 -> 파일 인코딩 메뉴 클릭 -> 프로퍼티 파일에 대한 디폴트 인코딩을 UTF-8로 설정.